//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meble_v1.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meble_v1.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Meble v 1.00.
        /// </summary>
        public static string App_name_and_version {
            get {
                return ResourceManager.GetString("App_name_and_version", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cofnij.
        /// </summary>
        public static string global_cofnij {
            get {
                return ResourceManager.GetString("global_cofnij", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz język.
        /// </summary>
        public static string mm_button_choose_language {
            get {
                return ResourceManager.GetString("mm_button_choose_language", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomoc.
        /// </summary>
        public static string mm_button_help {
            get {
                return ResourceManager.GetString("mm_button_help", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wczytaj zamówienie.
        /// </summary>
        public static string mm_button_load_order {
            get {
                return ResourceManager.GetString("mm_button_load_order", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stwórz nowe zamówienie.
        /// </summary>
        public static string mm_button_new_order {
            get {
                return ResourceManager.GetString("mm_button_new_order", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyjście.
        /// </summary>
        public static string mm_button_wyjscie {
            get {
                return ResourceManager.GetString("mm_button_wyjscie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz język aplikacji.
        /// </summary>
        public static string mm_choose_language {
            get {
                return ResourceManager.GetString("mm_choose_language", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dodaj szafkę.
        /// </summary>
        public static string nz_button_add_cupboard {
            get {
                return ResourceManager.GetString("nz_button_add_cupboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tworzenie nowego zamówienia.
        /// </summary>
        public static string nz_creating_new_order {
            get {
                return ResourceManager.GetString("nz_creating_new_order", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Drukuj zamówienie.
        /// </summary>
        public static string nz_print_order {
            get {
                return ResourceManager.GetString("nz_print_order", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz zamówienie.
        /// </summary>
        public static string nz_save_order {
            get {
                return ResourceManager.GetString("nz_save_order", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przeglądaj stworzone szafki.
        /// </summary>
        public static string nz_view_created_furnish {
            get {
                return ResourceManager.GetString("nz_view_created_furnish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Angielski.
        /// </summary>
        public static string uj_english {
            get {
                return ResourceManager.GetString("uj_english", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia języka.
        /// </summary>
        public static string uj_Language_selection {
            get {
                return ResourceManager.GetString("uj_Language_selection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polski.
        /// </summary>
        public static string uj_polish {
            get {
                return ResourceManager.GetString("uj_polish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa zamówienia: .
        /// </summary>
        public static string wsz_order_name {
            get {
                return ResourceManager.GetString("wsz_order_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podblatowa standard.
        /// </summary>
        public static string wsz_podblatowa_standard {
            get {
                return ResourceManager.GetString("wsz_podblatowa_standard", resourceCulture);
            }
        }
    }
}
